kind: Service
apiVersion: v1
metadata:
  name: wereld-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31002
  selector:
    app: wereld-service
